package dev.strataindustria.datagen;

import dev.strataindustria.StrataIndustria;
import dev.strataindustria.ceramics.MoldType;
import dev.strataindustria.geology.OreGrade;
import dev.strataindustria.geology.OreMineral;
import dev.strataindustria.geology.Rock;
import dev.strataindustria.heat.HeatBand;
import dev.strataindustria.material.Metal;
import dev.strataindustria.registry.ModBlocks;
import dev.strataindustria.registry.ModCreativeTabs;
import dev.strataindustria.registry.ModItems;
import dev.strataindustria.registry.Tier4Blocks;
import dev.strataindustria.registry.Tier4Items;
import java.util.Arrays;
import java.util.Locale;
import java.util.stream.Collectors;
import net.minecraft.data.PackOutput;
import net.neoforged.neoforge.common.data.LanguageProvider;

final class ModLanguageProvider extends LanguageProvider {
    ModLanguageProvider(PackOutput output) {
        super(output, StrataIndustria.MOD_ID, "en_us");
    }

    static String title(String id) {
        return Arrays.stream(id.split("_"))
                .map(word -> word.substring(0, 1).toUpperCase(Locale.ROOT) + word.substring(1))
                .collect(Collectors.joining(" "));
    }

    @Override
    protected void addTranslations() {
        add(ModCreativeTabs.MAIN_TAB_TITLE, "Strata Industria");
        StructureData.lang(this::add);
        Tier5Language.add(this::add);
        GridData.lang(this::add);
        FootData.lang(this::add);
        RailData.lang(this::add);
        RailwayData.lang(this::add);
        RopewayData.lang(this::add);
        TramData.lang(this::add);
        JournalLanguage.add(this::add);
        Tier6Data.lang(this::add);
        FellingData.lang(this::add);
        recipeViewer();

        addItem(ModItems.STRAW, "Straw");
        addItem(ModItems.CORD, "Bark Cord");
        addItem(ModItems.BARK_CLOTH, "Bark Cloth");
        addItem(ModItems.FIELD_JOURNAL, "Field Journal");
        addItem(ModItems.STONE_AXE, "Stone Axe");
        addItem(ModItems.STONE_KNIFE, "Stone Knife");
        addItem(ModItems.STONE_SHOVEL, "Stone Shovel");
        addItem(ModItems.STONE_HOE, "Stone Hoe");
        addItem(ModItems.STONE_HAMMER, "Stone Hammer");
        addItem(ModItems.STONE_PICKAXE, "Stone Pickaxe");

        String knapped = StrataIndustria.MOD_ID + ".knapped_from.";
        add(knapped + "rock", "Struck from %s");
        add(knapped + "flint", "Struck from flint");
        for (Rock rock : Rock.values()) {
            add(knapped + "material." + rock.id(), rock.id().replace('_', ' '));
        }
        addBlock(ModBlocks.FIRE_PIT, "Fire Pit");
        add("container." + StrataIndustria.MOD_ID + ".fire_pit", "Fire Pit");
        for (HeatBand band : HeatBand.values()) {
            String name = band.word();
            add(StrataIndustria.MOD_ID + ".heat." + (band == HeatBand.NONE ? "cold" : band.id()), name.substring(0, 1).toUpperCase(Locale.ROOT) + name.substring(1));
        }
        add(StrataIndustria.MOD_ID + ".flint_strike.need_rock", "Hold a rock in your other hand to strike the flint on");
        add(StrataIndustria.MOD_ID + ".knapping.need_more", "You need %s %s for this shape");
        add(StrataIndustria.MOD_ID + ".shaping.shape", "%s: %s blows, uses %s %s");
        add(StrataIndustria.MOD_ID + ".shaping.shape_bound", "%s: %s blows, uses %s %s, a stick and a cord");
        add(StrataIndustria.MOD_ID + ".shaping.need_binding", "A %s needs a stick and a cord in your pack");
        add(StrataIndustria.MOD_ID + ".shaping.progress", "%s  %s/%s");
        add(StrataIndustria.MOD_ID + ".shaping.done", "%s");
        add(StrataIndustria.MOD_ID + ".shaping.nothing", "Nothing to make from %s");
        add(StrataIndustria.MOD_ID + ".boulder.hint", "Hit it with your hand or a shard. Hold use to keep striking.");
        add(StrataIndustria.MOD_ID + ".shaping.hint", "Sneak + use (or scroll) picks the shape. Use strikes, hold to keep striking.");
        addItem(ModItems.UNFIRED_CRUCIBLE, "Unfired Crucible");
        addItem(ModItems.UNFIRED_INGOT_MOLD, "Unfired Ingot Mold");
        addItem(ModItems.UNFIRED_BRICK, "Unfired Brick");
        addBlock(ModBlocks.CRUCIBLE, "Crucible");
        addItem(ModItems.INGOT_MOLD, "Ingot Mold");
        for (MoldType type : MoldType.values()) {
            String name = title(type.id());
            addItem(ModItems.UNFIRED_MOLDS.get(type), "Unfired " + name + " Mold");
            addItem(ModItems.MOLDS.get(type), name + " Mold");
        }
        addBlock(ModBlocks.LOG_PILE, "Log Pile");
        addBlock(ModBlocks.CHARCOAL_PILE, "Charcoal Pile");
        addItem(ModItems.ASH, "Ash");
        addBlock(ModBlocks.FORGE, "Forge");
        addBlock(ModBlocks.QUERN, "Quern");
        smithing();
        journal();
        addItem(ModItems.QUERNSTONE, "Quernstone");
        add("container." + StrataIndustria.MOD_ID + ".forge", "Forge");
        metals();

        String subtitles = "subtitles." + StrataIndustria.MOD_ID + ".";
        add(subtitles + "clay.shape", "Clay squelches");
        add(subtitles + "clay.finish", "Clay piece formed");
        add(subtitles + "pit_kiln.log", "Log stacked");
        add(subtitles + "pit_kiln.fired", "Kiln burns out");
        add(subtitles + "heat.quench", "Hot metal hisses");
        add(subtitles + "heat.sear", "Skin sears");
        add(subtitles + "forge.ignite", "Forge catches");
        add(subtitles + "crucible.melt", "Metal melts");
        add(subtitles + "quern.grind", "Quern grinds");
        add(subtitles + "anvil.hit", "Hammer rings");
        add(subtitles + "prospect", "Pick taps rock");
        add(subtitles + "journal.open", "Pages turn");
        add(subtitles + "bloomery.light", "Bloomery catches");
        add(subtitles + "bloomery.roar", "Bloomery roars");
        add(subtitles + "bloomery.charge", "Bloomery charged");
        add(subtitles + "bloomery.done", "Bloom settles");
        add(subtitles + "bloomery.extract", "Bloom pulled out");
        add(subtitles + "raw_bloom.hit", "Bloom thuds");
        add(subtitles + "wrought_iron.hit", "Iron rings");
        add(subtitles + "anvil.done", "Piece finished");
        add(subtitles + "anvil.voice.copper", "Copper sings");
        add(subtitles + "anvil.voice.bronze", "Bronze rings");
        add(subtitles + "anvil.voice.iron", "Iron rings");
        add(subtitles + "anvil.voice.steel", "Steel rings");
        add(subtitles + "anvil.true_blow", "Hammer strikes true");
        add(subtitles + "anvil.cold", "Hammer thuds on cold metal");
        add(subtitles + "anvil.glint", "Hammer rebounds");
        add(subtitles + "anvil.set", "Piece set on the anvil");
        add(subtitles + "brick_kiln.work", "Brick kiln burns");
        add(subtitles + "brick_kiln.done", "Brick kiln fired");
        add(subtitles + "pattern.carve", "Wood carved");
        add(subtitles + "pattern.finish", "Pattern finished");
        add(subtitles + "pattern.press", "Pattern pressed into sand");
        add(subtitles + "casting_table.set", "Mold set down");
        add(subtitles + "casting_table.knock", "Castings knocked out");
        add(subtitles + "anvil.dress", "Stone dressed");
        add(subtitles + "anvil.weld", "Metal welds");
        add(subtitles + "anvil.stamp", "Mark struck");
        add(subtitles + "hand_crank.turn", "Crank creaks");
        add(subtitles + "water_wheel.turn", "Water wheel splashes");
        add(subtitles + "kinetic.overstress", "Machinery groans to a halt");
        add(subtitles + "millstone.grind", "Millstone grinds");
        add(subtitles + "bellows.pump", "Bellows wheeze");
        add(subtitles + "saw_mill.saw", "Saw rasps");
        add(subtitles + "saw_mill.blade_break", "Saw blade snaps");
        add(subtitles + "core_sampler.drill", "Core drill grinds");
        add(subtitles + "core_sampler.done", "Core sample ready");
        add(subtitles + "core_sample.open", "Core sample examined");
        add(subtitles + "sluice.wash", "Sluice water runs");
        add(subtitles + "windmill.turn", "Windmill creaks");
        add(subtitles + "belt.attach", "Belt fastened");
        add(subtitles + "soaking_barrel.seal", "Barrel lid thuds shut");
        add(subtitles + "soaking_barrel.open", "Barrel lid scrapes open");
        add(subtitles + "soaking_barrel.fill", "Water splashes into barrel");
        add(subtitles + "soaking_barrel.done", "Barrel soak finishes");
        add(subtitles + "washing_pan.swirl", "Pan swirls");
        add(subtitles + "washing_pan.find", "Something glints");
        add(subtitles + "anvil.weld_fail", "Weld refused");
        add(subtitles + "quern.load", "Quern loaded");
        add(subtitles + "quern.done", "Quern spills ground");
        add(subtitles + "crucible.pour", "Molten metal pours");
        add(subtitles + "mold.knock", "Cast knocked out");
        add(subtitles + "mold.break", "Mold cracks");
        add(subtitles + "boulder.strike", "Boulder knocked");
        add(subtitles + "boulder.crack", "Boulder cracks");
        add(subtitles + "boulder.split", "Boulder splits");
        add(subtitles + "boulder.shards", "Shards clatter");
        add(subtitles + "branch.shake", "Branch creaks");
        add(subtitles + "branch.snap", "Branch snaps");
        add(subtitles + "branch.bare", "Dry leaves rustle");
        add(subtitles + "cord.twist", "Bark fibres creak");
        add(subtitles + "cord.tight", "Cord snaps tight");
        add(subtitles + "cord.beat", "Cord thumps on stone");
        add(subtitles + "cord.cloth", "Bark cloth comes free");
        add("message." + StrataIndustria.MOD_ID + ".branch.bare", "This branch is bare. Try another.");
        add("jei.strataindustria.info.bark", "Snap a branch off a tree, or strip a log with an axe. Hold use with two strips in your hand to twist them into cord.");
        add("jei.strataindustria.info.cord", "Hold use with two bark strips to twist one. Use four cord on stone, three blows, to beat a cloth.");
        add("jei.strataindustria.info.bark_cloth", "Use four cord on stone. Three blows beat them flat and the cloth pops free.");
        add("jei.strataindustria.info.straw", "Break grass or ripe wheat by hand. A knife takes more.");
        add("message." + StrataIndustria.MOD_ID + ".cord.need_strips", "Two bark strips make a cord.");
        add("message." + StrataIndustria.MOD_ID + ".cord.need_cord", "Four cord make a cloth.");
        add(subtitles + "knapping.rock", "Stone chips");
        add(subtitles + "knapping.flint", "Flint chips");
        add(subtitles + "knapping.finish", "Stone breaks free");
        add(subtitles + "cord.bind", "Head bound on");
        add(subtitles + "shaping.chime", "Flint chimes");
        add(subtitles + "shaping.true_blow", "Strike lands true");
        add(subtitles + "shaping.glint", "Rebound ticks");
        add(subtitles + "crucible.fumes", "Fumes hiss");
        add(subtitles + "bell.ring", "Bell rings");
        add(subtitles + "cabinet.set", "Specimen set down");
        add(subtitles + "cabinet.shelf", "Shelf filled");
        add(subtitles + "flint.strike", "Flint strikes rock");
        add(subtitles + "flint.catch", "Tinder catches");
        add(subtitles + "fire_pit.ignite", "Fire catches");
        add(subtitles + "fire_pit.extinguish", "Fire goes out");
        add(subtitles + "fire_pit.torch", "Torch lit");
        add(subtitles + "fire_pit.set", "Clay set by the fire");
        add(subtitles + "fire_pit.ring", "Pottery rings");

        for (Rock rock : Rock.values()) {
            String name = title(rock.id());
            addBlock(ModBlocks.RAW_ROCK.get(rock), "Raw " + name);
            addBlock(ModBlocks.COBBLED_ROCK.get(rock), "Cobbled " + name);
            addBlock(ModBlocks.BOULDER.get(rock), name + " Boulder");
            addItem(ModItems.ROCK_SHARD.get(rock), name + " Shard");
            for (OreMineral mineral : OreMineral.inRockValues()) {
                addBlock(ModBlocks.ORES.get(rock).get(mineral), name + " " + title(mineral.id()) + " Ore");
            }
        }
        for (OreMineral mineral : OreMineral.values()) {
            String name = title(mineral.id());
            addBlock(ModBlocks.SMALL_ORES.get(mineral), "Small " + name);
            if (!mineral.hasPieces()) continue;
            for (OreGrade grade : OreGrade.values()) {
                String graded = grade == OreGrade.NORMAL ? name : title(grade.getSerializedName()) + " " + name;
                addItem(ModItems.ORE_PIECES.get(mineral).get(grade), graded);
                addItem(ModItems.CRUSHED_ORES.get(mineral).get(grade), "Crushed " + graded);
                if (mineral.washable()) addItem(ModItems.WASHED_ORES.get(mineral).get(grade), "Washed " + graded);
            }
        }
        ironAge();
        tier4();

        String config = StrataIndustria.MOD_ID + ".configuration.";
        add(config + "title", "Strata Industria Configs");
        add(config + "section." + StrataIndustria.MOD_ID + ".common.toml", "Strata Industria Configs");
        add(config + "section." + StrataIndustria.MOD_ID + ".common.toml.title", "Strata Industria Configs");
        add(config + "showDebugInfo", "Show debug info");
        add(config + "worldgen", "World Generation");
        add(config + "provinceScale", "Province size");
        add(config + "veinAttemptsPerCell", "Vein attempts per cell");
        add(config + "shallowBias", "Shallow vein bias");
        add(config + "emptyWeight", "Empty vein weight");
        add(config + "veinSizeMultiplier", "Vein size multiplier");
        add(config + "indicatorDepth", "Indicator depth");
        add(config + "indicatorDensity", "Indicator density");
        add(config + "spawnGuarantee", "Copper near spawn");
        add(config + "vanilla", "Vanilla Changes");
        add(config + "logsNeedAxe", "Logs need an axe");
        add(config + "removeWoodTools", "Remove wooden tools");
        add(config + "removeStoneTools", "Remove stone tools");
        add(config + "planksNeedTools", "Planks need tools");
        add(config + "removeCampfire", "Remove campfire recipe");
        add(config + "gateFurnace", "Gate the furnace");
        add(config + "replaceCopperGear", "Replace copper gear recipes");
        add(config + "branchSnapping", "Snap branches off trees");
        add(config + "gravelFlintChance", "More flint from gravel");
        add(config + "kiln", "Firing");
        add(config + "burnTicks", "Burn time (ticks)");
        add(config + "charcoal", "Charcoal Pit");
        add(config + "perLog", "Charcoal per log");
        add(config + "crucible", "Crucible");
        add(config + "capacity", "Capacity (units)");
        add(config + "casting", "Casting");
        add(config + "ingotMoldBreak", "Ingot mold break chance");
        add(config + "toolMoldBreak", "Tool mold break chance");
        add(config + "smithing", "Smithing");
        add(config + "randomTargets", "Random targets per world");
        add(config + "removeFurnaceCharcoal", "Remove furnace charcoal");
        add(config + "removeOreSmelting", "Remove ore smelting");
        add(config + "removeBlastFurnace", "Remove blast furnace recipe");
        add(config + "replaceIronGear", "Replace iron gear recipes");
        add(config + "replaceGoldGear", "Replace gold gear recipes");
        add(config + "golemDropsNuggets", "Iron golems drop nuggets");
        add(config + "hitCooling", "Cooling per hit on iron");
        add(config + "heat", "Item Heat");
        add(config + "burnPlayer", "Hot items burn bare hands");
        add(config + "bloomery", "Bloomery");
        add(config + "runTicks", "Bloomery run time");
        add(config + "journal", "Field Journal");
        add(config + "steam", "Steam");
        add(config + "blastFurnace", "Blast Furnace");
        add(config + "giveOnJoin", "Give a journal on first join");
    }

    /** Tier 3 spec 3 and 4: fire clay, the new deposits, and the wrought iron name for vanilla iron. */
    // Tier 4 spec 4.6: materials.
    private void tier4() {
        addItem(ModItems.STEEL_DOUBLE_INGOT, "Steel Double Ingot");
        addItem(dev.strataindustria.registry.Tier4Items.SULFUR, "Sulfur");
        addItem(dev.strataindustria.registry.Tier4Items.SULFUR_DUST, "Sulfur Dust");
        addItem(dev.strataindustria.registry.Tier4Items.CHARCOAL_DUST, "Charcoal Dust");

        // Tier 4 spec 5: coke, the coke oven and creosote.
        String id = StrataIndustria.MOD_ID;
        addItem(Tier4Items.COKE, "Coke");
        addItem(Tier4Items.COKE_DUST, "Coke Dust");
        addBlock(Tier4Blocks.COKE_BLOCK, "Block of Coke");
        addItem(Tier4Items.UNFIRED_COKE_OVEN_BRICK, "Unfired Coke Oven Brick");
        addItem(Tier4Items.COKE_OVEN_BRICK, "Coke Oven Brick");
        addBlock(Tier4Blocks.COKE_OVEN_BRICKS, "Coke Oven Bricks");
        addBlock(Tier4Blocks.COKE_OVEN_DOOR, "Coke Oven Door");
        addItem(Tier4Items.CREOSOTE_BUCKET, "Creosote Bucket");
        add("fluid_type." + id + ".creosote", "Creosote");
        addBlock(Tier4Blocks.TREATED_PLANKS, "Treated Planks");
        addBlock(Tier4Blocks.TREATED_SLAB, "Treated Slab");
        addBlock(Tier4Blocks.TREATED_STAIRS, "Treated Stairs");
        addBlock(Tier4Blocks.TREATED_FENCE, "Treated Fence");
        addItem(Tier4Items.TREATED_STICK, "Treated Stick");
        String oven = id + ".coke_oven.";
        add("container." + id + ".coke_oven", "Coke Oven");
        add(oven + "status.incomplete", "Oven incomplete");
        add(oven + "status.empty", "Empty");
        add(oven + "status.no_recipe", "This will not coke");
        add(oven + "status.working", "Baking... %s%%");
        add(oven + "status.output_full", "Output full");
        add(oven + "status.tank_full", "Creosote tank full");
        add(oven + "problem.brick", "Needs bricks at %s, %s, %s");
        add(oven + "problem.air", "Needs air at %s, %s, %s");
        add(oven + "tank", "Creosote %s / %s mB");
        add(oven + "tank_empty", "No creosote yet");
        String subtitles = "subtitles." + id + ".";
        add(subtitles + "coke_oven.working", "Coke oven smoulders");
        add(subtitles + "coke_oven.done", "Coke settles");
        add(subtitles + "creosote.fill", "Creosote glugs");
        add(subtitles + "crucible.carbon_burn", "Carbon burns off");
        add(subtitles + "crucible.calcine_reduce", "Calcine reduces");
        add(subtitles + "roasting.sizzle", "Ore roasts");
        add(subtitles + "roasting.done", "Calcine crumbles");

        // Spec 6: refractory ceramics and steel in the crucible.
        addItem(Tier4Items.UNFIRED_REFRACTORY_CRUCIBLE, "Unfired Refractory Crucible");
        addBlock(Tier4Blocks.REFRACTORY_CRUCIBLE, "Refractory Crucible");
        addItem(Tier4Items.UNFIRED_REFRACTORY_INGOT_MOLD, "Unfired Refractory Ingot Mold");
        addItem(Tier4Items.REFRACTORY_INGOT_MOLD, "Refractory Ingot Mold");
        addItem(Tier4Items.UNFIRED_REFRACTORY_GEAR_MOLD, "Unfired Refractory Gear Mold");
        addItem(Tier4Items.REFRACTORY_GEAR_MOLD, "Refractory Gear Mold");
        addItem(Tier4Items.UNFIRED_GEAR_MOLD, "Unfired Gear Mold");
        addItem(Tier4Items.GEAR_MOLD, "Gear Mold");
        add("container." + id + ".refractory_crucible", "Refractory Crucible");
        String status = id + ".crucible.status.";
        add(status + "at_limit", "Crucible at its limit (%s)");
        add(status + "carbon_waiting", "Carbon needs molten iron or calcine");
        add(status + "calcine_short", "Calcine needs more carbon");
        add(status + "carbon_burned", "Excess carbon burned off");
        String problem = id + ".crucible.problem.";
        add(problem + "mold_too_weak", "This mold cannot take metal this hot; use a refractory mold");
        add(problem + "no_gear", "That metal does not make gears");
        String config = id + ".configuration.";
        add(config + "clayMaxTemperature", "Clay crucible limit (°C)");
        add(config + "refractoryMoldBreak", "Refractory mold break chance");
        // Spec 4.4 and 5.3: zinc calcine and its gas.
        addItem(Tier4Items.ZINC_CALCINES.get(dev.strataindustria.geology.OreGrade.POOR), "Poor Zinc Calcine");
        addItem(Tier4Items.ZINC_CALCINES.get(dev.strataindustria.geology.OreGrade.NORMAL), "Zinc Calcine");
        addItem(Tier4Items.ZINC_CALCINES.get(dev.strataindustria.geology.OreGrade.RICH), "Rich Zinc Calcine");
        addItem(Tier4Items.SMALL_ZINC_CALCINE, "Small Zinc Calcine");
        add("fluid_type." + id + ".sulfur_dioxide", "Sulfur Dioxide");
        addBlock(Tier4Blocks.IRON_AXLE, "Iron Axle");
        addBlock(Tier4Blocks.IRON_GEARBOX, "Iron Gearbox");
        addBlock(Tier4Blocks.IRON_STEP_UP_GEARBOX, "Iron Step-up Gearbox");
        add(id + ".ore.sulfide", "Sulfide ore: roast it in a forge before melting");

        // Spec 8.1, 9 and 10: the firebox, pipes, the gauge and the bronze boiler.
        addBlock(Tier4Blocks.FIREBOX, "Firebox");
        addBlock(Tier4Blocks.BRONZE_BOILER, "Bronze Boiler");
        addBlock(Tier4Blocks.CRACKED_BRONZE_BOILER, "Cracked Bronze Boiler");
        addBlock(Tier4Blocks.CHUTE, "Chute");
        addBlock(Tier4Blocks.INSERTER, "Inserter");
        addBlock(Tier4Blocks.CONVEYOR_BELT, "Conveyor Belt");
        addBlock(Tier4Blocks.BELT_DIVERTER, "Belt Diverter");
        add(id + ".conveyor.flat", "Belt laid flat");
        add(id + ".conveyor.up", "Belt rises towards its end");
        add(id + ".conveyor.down", "Belt falls towards its end");
        add(id + ".conveyor.line_too_long", "A line of belts is %s long at most");
        addItem(Tier4Items.FILTER, "Filter");
        add("container." + id + ".filter", "Filter");
        String filter = id + ".filter.";
        add(filter + "empty", "Empty: set it up with right-click");
        add(filter + "whitelist", "Lets through:");
        add(filter + "blacklist", "Holds back:");
        add(filter + "tag", "Anything in #%s");
        add(filter + "grade_on", "Any ore grade");
        add(filter + "allow", "Let through");
        add(filter + "deny", "Hold back");
        add(filter + "any_grade", "Any grade");
        add(filter + "exact_grade", "Exact grade");
        add(filter + "set_hint", "Click with an item to add it");
        add(filter + "item_hint", "%s (right-click for its tags)");
        add(filter + "tag_entry", "Anything in #%s (right-click for the next)");
        add(subtitles + "chute.drop", "Chute clatters");
        add(subtitles + "block.inserter.swing", "Inserter whirrs");
        add(subtitles + "block.conveyor.run", "Conveyor rumbles");
        add(subtitles + "block.belt_diverter.push", "Diverter flicks an item aside");
        add(subtitles + "filter.configure", "Filter set");
        addBlock(Tier4Blocks.STEEL_BOILER_SHELL, "Steel Boiler Shell");
        addBlock(Tier4Blocks.BOILER_FLUID_PORT, "Boiler Fluid Port");
        addBlock(Tier4Blocks.BOILER_CONTROLLER, "Steel Boiler Controller");
        addBlock(Tier4Blocks.CRACKED_BOILER_CONTROLLER, "Cracked Steel Boiler Controller");
        addBlock(Tier4Blocks.COPPER_FLUID_PIPE, "Copper Fluid Pipe");
        addBlock(Tier4Blocks.BRONZE_FLUID_PIPE, "Bronze Fluid Pipe");
        addBlock(Tier4Blocks.STEEL_FLUID_PIPE, "Steel Fluid Pipe");
        addBlock(Tier4Blocks.PRESSURE_GAUGE, "Pressure Gauge");
        addBlock(Tier4Blocks.COPPER_HEAT_PIPE, "Copper Heat Pipe");
        addBlock(Tier4Blocks.REFRACTORY_HEAT_DUCT, "Refractory Heat Duct");
        addBlock(Tier4Blocks.HEAT_INLET, "Heat Inlet");
        addBlock(Tier4Blocks.INSULATED_COPPER_HEAT_PIPE, "Insulated Copper Heat Pipe");
        addBlock(Tier4Blocks.INSULATED_REFRACTORY_HEAT_DUCT, "Insulated Refractory Heat Duct");
        addBlock(Tier4Blocks.KILN, "Kiln");
        addItem(Tier4Items.SLAG_WOOL, "Slag Wool");
        add("container." + id + ".kiln", "Kiln");
        String kilnStatus = id + ".kiln.status.";
        add(kilnStatus + "empty", "Load clay to fire");
        add(kilnStatus + "no_recipe", "That does not fire");
        add(kilnStatus + "output_full", "Output full");
        add(kilnStatus + "needs_heat", "Needs heat");
        add(kilnStatus + "firing", "Firing (%s%%)");
        addBlock(Tier4Blocks.ROASTER, "Roaster");
        add("container." + id + ".roaster", "Roaster");
        String roaster = id + ".roaster.";
        add(roaster + "status.empty", "Load sulfide ore to roast");
        add(roaster + "status.no_recipe", "That does not roast");
        add(roaster + "status.output_full", "Output full");
        add(roaster + "status.needs_heat", "Needs heat");
        add(roaster + "status.roasting", "Roasting");
        add(roaster + "status.venting", "Venting sulfur dioxide");
        add(roaster + "tank", "Sulfur Dioxide %s / %s mB");
        addBlock(Tier4Blocks.SMELTER, "Smelter");
        add("container." + id + ".smelter", "Smelter");
        String smelter = id + ".smelter.";
        add(smelter + "auto_on", "Auto-pour: On");
        add(smelter + "auto_off", "Auto-pour: Off");
        add(smelter + "cooling", "%s");
        add(smelter + "slot.mold", "Mold being filled");
        add(smelter + "slot.stock", "Spare empty molds (up to 16)");
        add(smelter + "slot.cooling", "Filled mold cooling");
        add(smelter + "slot.output", "Castings");
        add(id + ".crucible.status.no_heat", "Needs heat from a firebox or heat pipes");
        add("fluid_type." + id + ".steam", "Steam");
        add("container." + id + ".firebox", "Firebox");
        add("container." + id + ".bronze_boiler", "Bronze Boiler");
        add("container." + id + ".boiler_controller", "Steel Boiler");
        String firebox = id + ".firebox.";
        add(firebox + "status.empty", "Add fuel");
        add(firebox + "status.idle", "Burning, %s HU/t wasted");
        add(firebox + "status.heating", "Heating: %s / %s HU/t");
        add(firebox + "status.cooling", "Out of fuel, cooling");
        add(firebox + "temperature", "%s");
        add(firebox + "blower", "Blower: hotter, 1.5× heat");
        // Spec 8.3: the line a multiblock shows about the heat coming in through its inlets.
        String heatLine = id + ".heat_line.";
        add(heatLine + "hot_blast", "Hot blast");
        add(heatLine + "preheat", "Preheat");
        add(heatLine + "kiln", "Heat");
        add(heatLine + "roaster", "Heat");
        add(heatLine + "smelter", "Heat");
        add(heatLine + "steam_hammer", "Heat");
        add(heatLine + "none", "%s: no heat");
        add(heatLine + "cold", "%s: %3$s, needs %2$s");
        add(heatLine + "limited", "%s: pipes cap it at %s");
        add(heatLine + "fine", "%s: %s, %s HU/t");
        add(heatLine + "limited_by", "Limited by %s (%s)");
        add(heatLine + "needs", "Needs %s");
        add(heatLine + "pipes", "the pipes");
        String boiler = id + ".boiler.";
        add(boiler + "status.no_heat", "No heat");
        add(boiler + "status.too_cool", "Fire too cool: %2$s, needs %1$s");
        add(boiler + "status.no_water", "No water");
        add(boiler + "status.heating", "Heating water (%s%%)");
        add(boiler + "status.running", "Making steam");
        add(boiler + "status.venting", "Venting: no demand");
        add(boiler + "status.pipe_too_hot", "Pipe too weak");
        add(boiler + "status.low_water", "Low water");
        add(boiler + "status.dry_firing", "Dry firing! %s%%");
        add(boiler + "pressure", "%s bar");
        add(boiler + "heat", "%s HU/t");
        add(boiler + "fire", "%s");
        add(boiler + "water", "Water %s / %s mB");
        add(boiler + "steam", "Steam %s / %s mB");
        add(boiler + "integrity", "Integrity %s%%");
        // Spec 10.3: what the steel boiler's structure lacks, by layer (1 is the fire) and spot.
        add(boiler + "problem.none", "Built");
        add(boiler + "problem.needs_fire", "Firebox or heat inlet: layer %s, %s");
        add(boiler + "problem.needs_shell", "Boiler shell: layer %s, %s");
        add(boiler + "problem.needs_water_port", "Needs a water port in the shell");
        add(boiler + "problem.needs_steam_port", "Needs a steam port in the shell");
        addBlock(Tier4Blocks.VALVE, "Valve");
        add(id + ".valve.held_shut", "Opened, but a redstone signal holds it shut");
        addBlock(Tier4Blocks.FLUID_TANK, "Fluid Tank");
        add(id + ".fluid_tank.empty", "Empty, holds %s mB (%s tanks)");
        add(id + ".fluid_tank.holds", "%s / %s mB of %s (%s tanks)");
        add(subtitles + "valve.open", "Valve opens");
        add(subtitles + "valve.close", "Valve shuts");
        add(subtitles + "fluid_tank.fill", "Tank fills");
        String gauge = id + ".pressure_gauge.";
        add(gauge + "empty", "Nothing flowing");
        add(gauge + "pressure", "Steam at %s bar");
        add(gauge + "flow", "%s flowing, %s mB/t");
        add(subtitles + "firebox.light", "Firebox catches");
        add(subtitles + "firebox.burn", "Firebox roars");
        add(subtitles + "heat_pipe.tick", "Heat pipe ticks");
        add(subtitles + "kiln.work", "Kiln roars");
        add(subtitles + "kiln.done", "Kiln batch fired");
        add(subtitles + "smelter.pour", "Smelter pours");
        add(subtitles + "smelter.bubble", "Molten metal bubbles");
        add(subtitles + "fluid_pipe.refuse", "Pipe clanks");
        add(subtitles + "boiler.heat", "Boiler creaks");
        add(subtitles + "boiler.run", "Boiler rumbles");
        add(subtitles + "boiler.vent", "Safety valve whistles");
        add(subtitles + "boiler.low_water", "Boiler warns of low water");
        add(subtitles + "boiler.dry_fire", "Boiler groans");
        add(subtitles + "boiler.steam_burst", "Steam bursts");
        add(subtitles + "boiler.crack", "Boiler cracks");
        add(subtitles + "boiler.repair", "Boiler patched");
        add(config + "boilerExplosions", "Cracking boilers explode");
        add(config + "dryFiringDamagePerSecond", "Dry firing damage per second (%)");
        add(config + "engineCapacity", "Steam engine capacity (SU)");
        addBlock(Tier4Blocks.MECHANICAL_PUMP, "Mechanical Pump");
        addBlock(Tier4Blocks.STEAM_ENGINE, "Steam Engine");
        addBlock(Tier4Blocks.STEAM_HAMMER, "Steam Hammer");
        add("container." + id + ".steam_hammer", "Steam Hammer");
        String steamHammer = id + ".steam_hammer.";
        add(steamHammer + "status.waiting", "Waiting for a workpiece");
        add(steamHammer + "status.wrong_piece", "The shape does not fit this piece");
        add(steamHammer + "status.output_full", "Output full");
        add(steamHammer + "status.no_steam", "Needs steam at 1 bar or more");
        add(steamHammer + "status.too_cold", "Workpiece too cold");
        add(steamHammer + "status.heating", "Heating the piece: %s, needs %s");
        add(steamHammer + "status.working", "Working (%s / %s hits)");
        add(steamHammer + "steam.none", "Steam: none");
        add(steamHammer + "steam.slow", "Steam: %s bar, half speed");
        add(steamHammer + "steam.full", "Steam: %s bar");
        add(steamHammer + "buffer", "Steam: %s / %s mB");
        add(steamHammer + "slot.input", "Workpieces, cold or hot");
        add(steamHammer + "slot.piece", "On the anvil");
        add(steamHammer + "slot.result", "Finished pieces");
        add(subtitles + "steam_hammer.strike", "Steam hammer strikes");
        String engine = id + ".steam_engine.";
        addBlock(dev.strataindustria.listening.ListeningBlocks.STEAM_WHISTLE, "Steam Whistle");
        addBlock(dev.strataindustria.flora.FloraBlocks.PLANTS.get(dev.strataindustria.flora.IndicatorPlant.COPPER_FLOWER), "Copper Flower");
        addBlock(dev.strataindustria.flora.FloraBlocks.PLANTS.get(dev.strataindustria.flora.IndicatorPlant.HORSETAIL), "Horsetail");
        addBlock(dev.strataindustria.flora.FloraBlocks.PLANTS.get(dev.strataindustria.flora.IndicatorPlant.STUNTED_BIRCH), "Stunted Birch");
        addBlock(dev.strataindustria.flora.FloraBlocks.PLANTS.get(dev.strataindustria.flora.IndicatorPlant.PINK_THRIFT), "Pink Thrift");
        addBlock(dev.strataindustria.flora.FloraBlocks.PLANTS.get(dev.strataindustria.flora.IndicatorPlant.LOCOWEED), "Locoweed");
        add(subtitles + "tap.ring", "Ore rings clean");
        add(subtitles + "tap.knock", "Hammer knocks");
        add(subtitles + "tap.thud", "Hammer thuds dully");
        add(subtitles + "belt.squeal", "Belt squeals");
        add(subtitles + "gear.tick", "Gears tick");
        add(subtitles + "water_wheel.groan", "Water wheel groans");
        add(subtitles + "steam_engine.knock", "Steam engine knocks");
        add(subtitles + "boiler.hiss", "Boiler hisses");
        add(subtitles + "steam_whistle.blow", "Steam whistle blows");
        addItem(dev.strataindustria.mark.MarkRegistry.MAKER_PUNCH, "Maker's Punch");
        add("container." + id + ".makers_mark", "Your mark");
        add(id + ".mark.stamp", "Keep it");
        add(id + ".mark.clear", "Clear");
        add(id + ".mark.blank", "Cut at least one cell first");
        add(id + ".mark.made_by", "Made by %s");
        add(id + ".mark.mined", "%s blocks mined");
        add(subtitles + "mark.stamp", "Mark stamped");
        add(subtitles + "mark.cut", "Punch taps");
        addBlock(dev.strataindustria.registry.TransportBlocks.OUTPOST_CHARTER, "Outpost Charter");
        add(id + ".outposts.too_close", "Too close to another charter. It is %s blocks off; charters need %s between them.");
        add(id + ".outposts.too_many", "That is all the charters allowed (%s).");
        add(id + ".outposts.no_charter", "No charter at one end of that line.");
        add(id + ".outposts.district_full", "A district can hold %s charters.");
        add(id + ".outposts.opened", "The %s from %s to %s runs.");
        add(id + ".outposts.cut", "The %s from %s to %s is cut at %s.");
        add(id + ".outposts.outline_none", "This charter loads nothing right now.");
        add(id + ".outposts.kind.tramway", "tramway");
        add(id + ".outposts.kind.railway", "railway");
        add(id + ".outposts.kind.railway_mixed", "railway (wooden sections)");
        add(id + ".outposts.kind.ropeway", "ropeway");
        add(id + ".outposts.kind.tram", "tram line");
        add(id + ".outposts.kind.power", "power line");
        add(id + ".outposts.kind.telegraph", "telegraph");
        add(id + ".outposts.kind.pipeline", "pipeline");
        add(id + ".outposts.board.name", "Charter name");
        add(id + ".outposts.board.owner", "Owner %s");
        add(id + ".outposts.board.done", "Done");
        add(id + ".outposts.board.area_loaded", "Area: %s x %s chunks, loaded");
        add(id + ".outposts.board.area_waiting", "Area: %s x %s chunks, not loaded while no owner is on");
        add(id + ".outposts.board.no_line", "No line.");
        add(id + ".outposts.board.chunk_limit", "Chunk limit reached. Not loaded.");
        add(id + ".outposts.board.cut_to_fit", "Area cut to %s x %s: chunk limit.");
        add(id + ".outposts.board.lines", "Lines:");
        add(id + ".outposts.board.line", "%s to %s");
        add(id + ".outposts.board.open", "open, %s blocks");
        add(id + ".outposts.board.cut", "cut at %s");
        add(id + ".outposts.board.more", "and %s more");
        add(id + ".outposts.board.traffic_none", "Last traffic: none yet");
        add(id + ".outposts.board.traffic_now", "Last traffic: just now");
        add(id + ".outposts.board.traffic_minutes", "Last traffic: %s min ago");
        add(id + ".outposts.board.traffic_hours", "Last traffic: %s h ago");
        add(subtitles + "charter.place", "Charter posted");
        add(subtitles + "charter.line_cut", "Line cut");
        add(subtitles + "charter.deed", "Deed written");
        addItem(dev.strataindustria.ledger.LedgerRegistry.BUILDERS_LEDGER, "Builder's Ledger");
        addBlock(dev.strataindustria.bronze.BronzeRegistry.FUME_HOOD, "Fume Hood");
        add("item." + StrataIndustria.MOD_ID + ".fume_hood.hint", "Set it directly above a crucible. Arsenic fumes rise while the pot is poured.");
        add("item." + StrataIndustria.MOD_ID + ".bell.hint", "Hangs from the underside of a block. Right-click to ring.");
        addBlock(dev.strataindustria.cabinet.CabinetRegistry.SPECIMEN_CABINET, "Specimen Cabinet");
        String cab = StrataIndustria.MOD_ID + ".cabinet.";
        add(cab + "have", "%s is already in the cabinet");
        add(cab + "set", "%s on the shelf (%s of %s)");
        add(cab + "full", "%s shelf full");
        add(cab + "status", "%s of %s specimens, %s of %s shelves full");
        add(cab + "shelf.igneous_extrusive", "Extrusive igneous");
        add(cab + "shelf.igneous_intrusive", "Intrusive igneous");
        add(cab + "shelf.metamorphic", "Metamorphic");
        add(cab + "shelf.sedimentary", "Sedimentary");
        add(cab + "shelf.minerals", "Mineral");
        addBlock(dev.strataindustria.bronze.BronzeRegistry.BELL, "Bell");
        addItem(dev.strataindustria.bronze.BronzeRegistry.UNFIRED_BELL_MOLD, "Unfired Bell Mold");
        addItem(dev.strataindustria.bronze.BronzeRegistry.BELL_MOLD, "Bell Mold");
        add(StrataIndustria.MOD_ID + ".fumes.sting", "The fumes sting. Get out of the room");
        addBlock(dev.strataindustria.ledger.LedgerRegistry.BUILDERS_CRATE, "Builder's Crate");
        add(id + ".ledger.plan.coke_oven", "coke oven");
        add(id + ".ledger.plan.blast_furnace", "blast furnace");
        add(id + ".ledger.plan.converter", "converter");
        add(id + ".ledger.plan.steel_boiler", "steel boiler");
        add(id + ".ledger.entered", "Entered in the ledger: %s.");
        add(id + ".ledger.known", "Already in the ledger.");
        add(id + ".ledger.unknown", "No %s in the ledger yet. Build one by hand first.");
        add(id + ".ledger.busy", "Already at it.");
        add(id + ".ledger.nothing_to_do", "Nothing to place.");
        add(id + ".ledger.in_the_way", "Other blocks are in the way.");
        add(id + ".ledger.short", "Out of blocks. %s more %s needed.");
        add(id + ".ledger.done", "Stamped. %s blocks placed.");
        add(id + ".ledger.done_in_the_way", "Stamped %s blocks. %s spots had other blocks in them.");
        add(id + ".multiblock.incomplete", "Structure incomplete: %s at %s");
        add(id + ".multiblock.empty_space", "empty space");
        add(id + ".ledger.tooltip.enter", "Use on a finished multiblock to enter it.");
        add(id + ".ledger.tooltip.stamp", "Use on an unfinished one to place it from crates nearby.");
        add(subtitles + "ledger.entry", "Ledger written");
        add(subtitles + "ledger.stamp", "Block stamped into place");
        add(subtitles + "ledger.short", "Ledger shut");
        add(engine + "no_steam", "No steam");
        add(engine + "low_pressure", "Steam pressure under 1 bar");
        add(engine + "running", "%s RPM on %s bar");
        String pump = id + ".mechanical_pump.status.";
        add(pump + "not_turning", "Not turning");
        add(pump + "too_slow", "Too slow: needs 8 RPM");
        add(pump + "no_water", "No water source at the intake");
        add(pump + "no_outlet", "No pipe at the outlet");
        add(pump + "outlet_full", "Nothing takes the water");
        add(pump + "pumping", "Pumping %s mB/t");
        add(subtitles + "steam_engine.chuff", "Steam engine chuffs");
        add(subtitles + "steam_engine.start", "Steam engine starts");
        add(subtitles + "steam_engine.stop", "Steam engine stops");
        add(subtitles + "mechanical_pump.run", "Pump thumps");
        addBlock(Tier4Blocks.CRUSHER, "Crusher");
        add("container." + id + ".crusher", "Crusher");
        add(subtitles + "crusher.crush", "Crusher grinds");
        addBlock(Tier4Blocks.WASHER, "Washer");
        add("container." + id + ".washer", "Washer");
        add(subtitles + "washer.wash", "Washer sloshes");
        add(id + ".machine.no_water", "Needs water: pipe it in");
        add(id + ".washer.water", "Water: %s / %s mB");

        // Spec 12.1 and 11.6: the blast furnace and the blower.
        addBlock(Tier4Blocks.REFRACTORY_CASING, "Refractory Casing");
        addBlock(Tier4Blocks.BLAST_FURNACE_CONTROLLER, "Blast Furnace Controller");
        addBlock(Tier4Blocks.TUYERE, "Tuyere");
        addBlock(Tier4Blocks.CHARGING_HATCH, "Charging Hatch");
        addBlock(Tier4Blocks.TAP_HATCH, "Tap Hatch");
        addBlock(Tier4Blocks.BLOWER, "Blower");
        addBlock(Tier4Blocks.BLOWING_ENGINE, "Blowing Engine");
        add(id + ".blowing_engine.full", "Blowing hard, worth two blowers (%s bar)");
        add(id + ".blowing_engine.half", "Half stroke, worth one blower (%s bar)");
        add(id + ".blowing_engine.no_steam", "Needs steam at 1 bar or more at the back");
        add("subtitles." + id + ".blowing_engine.stroke", "Blowing engine chuffs");
        addItem(Tier4Items.SLAG, "Slag");
        addItem(Tier4Items.SLAG_DUST, "Slag Dust");
        add("container." + id + ".blast_furnace", "Blast Furnace");
        String furnace = id + ".blast_furnace.";
        add(furnace + "status.incomplete", "Structure incomplete");
        add(furnace + "status.no_air", "No air blast");
        add(furnace + "status.needs_fuel", "Needs coke");
        add(furnace + "status.heating", "Heating hearth (%s%%)");
        add(furnace + "status.needs_iron", "Needs iron");
        add(furnace + "status.needs_flux", "Needs flux");
        add(furnace + "status.output_full", "Output full");
        add(furnace + "status.running", "Running, air from %s blower(s)");
        add(furnace + "problem.needs_casing", "Refractory casing: layer %s, %s");
        add(furnace + "problem.needs_refractory", "Refractory block: layer %s, %s");
        add(furnace + "problem.needs_air", "Clear the shaft: layer %s, %s");
        add(furnace + "problem.needs_charging_hatch", "Charging hatch: layer %s, %s");
        add(furnace + "problem.needs_tap_hatch", "Tap hatch: layer %s, an edge");
        add(furnace + "problem.needs_tuyere", "Tuyere: layer %s, an edge");
        String[] spots = {"front left", "front", "front right", "middle left", "middle", "middle right", "back left", "back", "back right"};
        for (int i = 0; i < spots.length; i++) add(furnace + "spot." + i, spots[i]);
        add(furnace + "iron", "Iron: %s / %s units");
        add(furnace + "fuel", "Coke: %s / %s");
        add(furnace + "flux", "Flux: %s / %s");
        add(furnace + "hearth", "Hearth heat: %s%%");
        add(subtitles + "blower.run", "Blower whooshes");
        add(subtitles + "blast_furnace.roar", "Blast furnace roars");
        add(subtitles + "blast_furnace.tap", "Pig iron pours");
        add(subtitles + "multiblock.form", "Structure complete");
        addBlock(Tier4Blocks.CONVERTER_CONTROLLER, "Converter Controller");
        add("container." + id + ".converter", "Converter");
        String converter = id + ".converter.";
        add(converter + "status.incomplete", "Structure incomplete");
        add(converter + "status.empty", "Needs pig iron");
        add(converter + "status.charging", "Charging: waiting for more pig iron");
        add(converter + "status.no_air", "No air blast");
        add(converter + "status.needs_preheat", "Needs preheat: add a coke");
        add(converter + "status.output_full", "Output full");
        add(converter + "status.blowing", "Blowing (%s%%)");
        add(converter + "charge_pig", "Pig iron in the blow: %s / %s");
        add(converter + "charge_scrap", "Scrap in the blow: %s / %s");
        add(converter + "preheated", "Preheated with coke");
        add(converter + "not_preheated", "One coke preheats each blow");
        add(converter + "flame", "The flame climbs to white, then drops when the steel is done");
        add(subtitles + "converter.blow", "Converter roars");
        add(subtitles + "converter.done", "Converter blow ends");
        add(config + "ticksPerIngot", "Ticks per pig iron ingot");
        add(config + "warmupTicks", "Hearth warm-up (ticks)");
    }

    private void ironAge() {
        String id = StrataIndustria.MOD_ID;
        addItem(ModItems.FIRE_CLAY_BALL, "Fire Clay Ball");
        addItem(ModItems.GROG, "Grog");
        addItem(ModItems.UNFIRED_FIRE_BRICK, "Unfired Fire Brick");
        addItem(ModItems.FIRE_BRICK, "Fire Brick");
        addBlock(ModBlocks.FIRE_CLAY, "Fire Clay");
        addBlock(ModBlocks.FIRE_BRICKS, "Fire Bricks");
        addBlock(ModBlocks.FIRE_BRICK_SLAB, "Fire Brick Slab");
        addBlock(ModBlocks.FIRE_BRICK_STAIRS, "Fire Brick Stairs");
        addBlock(ModBlocks.FIRE_BRICK_WALL, "Fire Brick Wall");
        addItem(ModItems.LIGNITE, "Lignite");
        addBlock(ModBlocks.LIGNITE_SEAM, "Lignite Seam");
        addBlock(ModBlocks.BAUXITE_BED, "Bauxite Bed");
        addItem(ModItems.BAUXITE, "Bauxite");
        addBlock(ModBlocks.BOG_IRON, "Bog Iron");
        addBlock(ModBlocks.PLACER_GRAVEL, "Placer Gravel");
        addBlock(ModBlocks.PLACER_SAND, "Placer Sand");
        addItem(ModItems.WROUGHT_IRON_ROD, "Wrought Iron Rod");
        addItem(ModItems.WROUGHT_IRON_DOUBLE_INGOT, "Wrought Iron Double Ingot");
        // Spec 2: the vanilla iron ingot and nugget are wrought iron.
        add("item.minecraft.iron_ingot", "Wrought Iron Ingot");
        add("item.minecraft.iron_nugget", "Wrought Iron Nugget");
        add(id + ".ore.lignite_seam", "lignite");
        add(id + ".ore.bauxite_bed", "bauxite");
        add(id + ".ore.fire_clay", "fire clay");
        add(id + ".prospect.rich", ", rich ore nearby");
        add(id + ".crucible.no_iron", "Iron does not melt this hot");

        // Spec 5: the bloomery.
        addBlock(ModBlocks.BLOOMERY, "Bloomery");
        addItem(ModItems.RAW_BLOOM, "Raw Bloom");
        addItem(ModItems.BLOOMERY_SLAG, "Bloomery Slag");
        String bloomery = id + ".bloomery.";
        add("container." + id + ".bloomery", "Bloomery");
        add(bloomery + "status.incomplete", "Structure incomplete");
        add(bloomery + "status.empty", "Empty");
        add(bloomery + "status.charged", "Charged, ready to light");
        add(bloomery + "status.needs_charcoal", "Needs %s more charcoal");
        add(bloomery + "status.heating", "Heating (%s)");
        add(bloomery + "status.too_cool", "Too cool: needs yellow heat");
        add(bloomery + "status.burning", "Burning (%s%%)");
        add(bloomery + "status.ready", "Bloom ready: use a pickaxe");
        add(bloomery + "problem.brick", "Needs fire bricks");
        add(bloomery + "problem.air", "Needs to be open");
        add(bloomery + "at", "at %s, %s, %s");
        add(bloomery + "hint", "Bricks around and under the chamber.");
        add(bloomery + "charge", "Ore %s/%s, charcoal %s/%s");
        add(bloomery + "draught", "Flue %s, bellows %s: %s");
        add(bloomery + "yield", "Yield %s%%, %s blooms");
        add(bloomery + "no_yield", "Too cool for a bloom");
        add(bloomery + "not_iron", "Only iron-bearing items go in a bloomery");
        add(bloomery + "lignite", "Lignite burns too cool for a bloomery");
        add(bloomery + "busy", "Not while it burns or holds a bloom");
        add(bloomery + "full", "The bloomery is full");
        add(bloomery + "bloom_units", "%s units of iron");
    }

    /** Spec 11: the field journal's goals and hints. */
    private void journal() {
        String journal = "journal." + StrataIndustria.MOD_ID + ".";
        add(journal + "root", "Field Journal");
        add(journal + "root.hint", "Every goal of the field journal at a glance. Switch this tab on in the config to open it from the journal.");
        add(journal + "t0.boulder", "Boulder");
        add(journal + "t0.boulder.hint", "Hit a boulder with your bare hand until it splits, then pick up a shard.");
        add(journal + "t0.knap", "First Edge");
        add(journal + "t0.knap.hint", "Hold two rock shards or one flint, with a stick and a cord in your pack. Sneak and use picks the tool, use strikes. Four blows and it comes off bound.");
        add(journal + "t0.stone_axe", "Stone Axe");
        add(journal + "t0.stone_axe.hint", "Strike an axe from a shard. Pick the axe shape first.");
        add(journal + "t0.log", "Timber");
        add(journal + "t0.log.hint", "Fell a tree with your axe. Bare hands will not do.");
        add(journal + "t0.crafting_table", "A Proper Workbench");
        add(journal + "t0.crafting_table.hint", "Build a crafting table.");
        add(journal + "t0.twine", "Bark Cord");
        add(journal + "t0.twine.hint", "Snap a branch off a tree for bark strips. Hold use with two strips to twist them into cord.");
        add(journal + "t0.fire", "Firelight");
        add(journal + "t0.fire.hint", "Build a fire pit from sticks and straw, put fuel in, and strike flint on a rock over it.");
        add(journal + "t0.clay", "Riverbank Clay");
        add(journal + "t0.clay.hint", "Gather five clay balls. Look along riverbanks and in swamps.");
        add(journal + "t1.clay_forming", "Shaped by Hand");
        add(journal + "t1.clay_forming.hint", "Hold five clay balls and use them. Sneak and use picks what to form; strike a few times and it is done.");
        add(journal + "t1.fired_pottery", "Fired Pottery");
        add(journal + "t1.fired_pottery.hint", "Set an unfired piece on the stones beside a lit fire pit. Charcoal or logs burn hot enough. Wait until it rings.");
        add(journal + "t1.charcoal", "Charcoal Burner");
        add(journal + "t1.charcoal.hint", "Sneak and place logs into a pile, light it, cover every face with soil or stone, then dig out the charcoal.");
        add(journal + "t1.forge", "The Forge");
        add(journal + "t1.forge.hint", "Build a forge. It burns charcoal far hotter than a fire pit.");
        add(journal + "t1.nugget", "Signs in the Soil");
        add(journal + "t1.nugget.hint", "Find a small ore on the surface. A vein lies somewhere below it.");
        add(journal + "t1.crucible", "Crucible and Mold");
        add(journal + "t1.crucible.hint", "Fire a crucible and an ingot mold on the fire pit.");
        add(journal + "t2.melt", "Molten");
        add(journal + "t2.melt.hint", "Set a crucible on top of a lit forge and melt ore in it.");
        add(journal + "t2.copper_ingot", "First Metal");
        add(journal + "t2.copper_ingot.hint", "Pour molten copper into an ingot mold and knock the ingot out once it cools.");
        add(journal + "t2.copper_pickaxe", "Copper Pick");
        add(journal + "t2.copper_pickaxe.hint", "Make a copper pickaxe. It breaks ore a stone pick cannot.");
        add(journal + "t2.alloy_metal", "Tin, Bismuth or Arsenic");
        add(journal + "t2.alloy_metal.hint", "Mine cassiterite, bismuthinite or tennantite ore.");
        add(journal + "t2.quern", "Ground Fine");
        add(journal + "t2.quern.hint", "Knap a quernstone from four rock shards and stack two under a stick for a quern. Put ore in and keep turning it; crushed ore melts down to more metal.");
        add(journal + "t2.bronze", "Bronze Age");
        add(journal + "t2.bronze.hint", "Melt 3 parts copper with 1 part tin, or copper with bismuth or arsenic, and cast a bronze ingot.");
        add(journal + "t2.stone_anvil", "Dressed Stone");
        add(journal + "t2.stone_anvil.hint", "Sneak and strike the top of raw igneous rock with a hammer to dress it into an anvil for copper and bronze.");
        add(journal + "t2.smith", "Hammer Work");
        add(journal + "t2.smith.hint", "Heat an ingot in the forge and lay it on an anvil. Sneak and use a hammer to pick a shape, then strike.");
        add(journal + "t2.bronze_tools", "Full Kit");
        add(journal + "t2.bronze_tools.hint", "Own a bronze pickaxe, axe, shovel, knife, hammer, saw and sword.");
        add(journal + "t2.bronze_armour", "Clad in Bronze");
        add(journal + "t2.bronze_armour.hint", "Wear a full set of bronze armour.");
        add(journal + "t2.prospectors_pick", "Listening to the Rock");
        add(journal + "t2.prospectors_pick.hint", "Strike rock with a prospector's pick to learn what ore lies nearby.");
        add(journal + "t3.fire_clay", "Fire Clay");
        add(journal + "t3.fire_clay.hint", "Bronze cannot melt iron. You will need a bloomery, and it is built of fire bricks. "
                + "Dig fire clay from the pale beds near the surface in shale and slate.");
        add(journal + "t3.fire_brick", "Fire Brick");
        add(journal + "t3.fire_brick.hint", "Form fire clay into bricks and fire them on the fire pit.");
        add(journal + "t3.iron_ore", "Iron Ore");
        add(journal + "t3.iron_ore.hint", "Iron hides in shale and slate, under swamps, and deep in dark igneous rock. "
                + "Your prospector's pick can find it.");
        add(journal + "t3.bloomery", "Bloomery");
        add(journal + "t3.bloomery.hint", "A bloomery is a chimney of fire bricks with a door in front. Two levels are enough to start.");
        add(journal + "t3.bloom", "Iron Bloom");
        add(journal + "t3.bloom.hint", "Charge the bloomery with iron ore and charcoal, light it, and wait for the bloom.");
        add(journal + "t3.refine", "Wrought Iron");
        add(journal + "t3.refine.hint", "Hammer a hot bloom on a stone anvil to squeeze out the slag.");
        add(journal + "t3.iron_pickaxe", "Iron Pickaxe");
        add(journal + "t3.iron_pickaxe.hint", "Smith a wrought iron pickaxe head and fit it to a handle.");
        add(journal + "t3.bucket", "Bucket");
        add(journal + "t3.bucket.hint", "Wrought iron is finally enough for a bucket.");
        add(journal + "t3.furnace", "Furnace");
        add(journal + "t3.furnace.hint", "Eight fire bricks make a furnace.");
        add(journal + "t3.rotation", "Turning");
        add(journal + "t3.rotation.hint", "Put a hand crank on the end of a wooden axle and hold right-click on it.");
        add(journal + "t3.water_power", "Water Power");
        add(journal + "t3.water_power.hint", "Set a water wheel on an axle where flowing water pushes one side of it.");
        add(journal + "t3.millstone", "Millstone");
        add(journal + "t3.millstone.hint", "Drive a millstone from an axle and let it grind for you.");
        add(journal + "t3.bellows", "Bellows");
        add(journal + "t3.bellows.hint", "Turn a bellows with a shaft and point its nozzle into a forge or a bloomery wall.");
        add(journal + "t3.saw_mill", "Saw Mill");
        add(journal + "t3.saw_mill.hint", "Fit a saw blade to a saw mill and saw a log: six planks and the bark.");
        add(journal + "t3.trip_hammer", "Trip Hammer");
        add(journal + "t3.wash", "Panning");
        add(journal + "t3.wash.hint", "Scoop placer gravel from a river bed with a washing pan and swirl it standing in water.");
        add(journal + "t3.core_sample", "Core Sample");
        add(journal + "t3.core_sample.hint", "Turn a core sampler and press Drill to read the ground 64 blocks down.");
        add(journal + "t3.trip_hammer.hint", "Put a hot workpiece in a trip hammer, or leave hot pieces in a forge beside its anvil. Pick the shape with the button on its screen.");
        add(journal + "t3.charter", "Found an Outpost");
        add(journal + "t3.charter.hint", "A charter post holds an outpost once a line runs to it. Lay track to it and send a tub through.");
        add(journal + "t3.weld", "Forge Weld");
        add(journal + "t3.weld.hint", "Heat two iron ingots, lay both on the iron anvil and strike them together into a double ingot. No flux needed.");
        add(journal + "t2.brick_kiln", "Brick Kiln");
        add(journal + "t2.brick_kiln.hint", "Build a brick kiln out of bricks, set it on a lit forge, and fire clay pieces in it.");
        add(journal + "t2.pattern_casting", "Pattern Casting");
        add(journal + "t2.pattern_casting.hint", "Cut a plank blank from planks and strike it into a pattern (sneak and use picks the shape). Press the pattern into a sand flask (right-click with a flask in your pack) to get a sand mold. A sand mold takes any metal, once.");
        add(journal + "t2.casting_table", "Casting Table");
        add(journal + "t2.casting_table.hint", "Lay fired molds on a casting table beside a crucible and pour. One pour fills every empty mold. Click the table to knock the castings out.");
        add(journal + "t2.bright_strike", "Struck Bright");
        add(journal + "t2.bright_strike.hint", "Finish a piece without letting the metal dull. Strike while it glows, and go back to the forge when it fades.");
        add(journal + "t3.hide", "Raw Hide");
        add(journal + "t3.hide.hint", "Animals give raw hides now. Leather has to be tanned.");
        add(journal + "t3.leather", "Tanned Leather");
        add(journal + "t3.leather.hint", "Soak raw hides in tannin from bark, in a sealed barrel.");
        add(journal + "t3.iron_anvil", "Iron Anvil");
        add(journal + "t3.iron_anvil.hint", "Build an iron anvil from seven iron ingots. Stone anvils cannot work iron or steel.");
        add(journal + "t4.coal", "Black Rock");
        add(journal + "t4.coal.hint", "Coal lies in deep shale and arkose seams. Bronze will not cut it.");
        add(journal + "t4.coke_oven", "Coke Oven");
        add(journal + "t4.coke_oven.hint", "Fire coke oven bricks and build a hollow 3x3x3 oven with a door in the middle of one side.");
        add(journal + "t4.coke", "Coke");
        add(journal + "t4.coke.hint", "Bake coal in the coke oven. Coke burns hot enough to melt steel.");
        add(journal + "t4.creosote", "Creosote");
        add(journal + "t4.creosote.hint", "Draw the creosote from the oven into a bucket and treat planks with it.");
        add(journal + "t4.refractory_crucible", "Refractory Crucible");
        add(journal + "t4.refractory_crucible.hint", "Form a crucible from fire clay and fire it. It stands the heat of melting iron.");
        add(journal + "t4.molten_iron", "Molten Iron");
        add(journal + "t4.molten_iron.hint", "Melt iron in a refractory crucible on a forge burning coke, with bellows.");
        add(journal + "t4.steel", "Crucible Steel");
        add(journal + "t4.steel.hint", "Stir coke or charcoal dust into molten iron, one dust to five ingots, and cast it in a refractory mold.");
        add(journal + "t4.sphalerite", "Zinc Blende");
        add(journal + "t4.sphalerite.hint", "Find sphalerite. Zinc is the key to brass.");
        add(journal + "t4.roast", "Roasted Ore");
        add(journal + "t4.roast.hint", "Zinc ore must be roasted before it will melt. A hot forge will do.");
        add(journal + "t4.brass", "Brass");
        add(journal + "t4.brass.hint", "Melt calcine with copper and a little carbon dust. Two parts copper to one of zinc.");
        add(journal + "t4.solder", "Solder");
        add(journal + "t4.solder.hint", "Galena melts like tin ore. Alloy its lead with tin.");
        add(journal + "t4.pipe", "Pipework");
        add(journal + "t4.pipe.hint", "Join copper plates with solder into pipe. Copper carries a bronze boiler's steam.");
        add(journal + "t4.boiler", "Raising Steam");
        add(journal + "t4.boiler.hint", "Set a bronze boiler on a burning firebox, fill it with water and wait for the needle to rise.");
        add(journal + "t4.heat_network", "Heat on the Move");
        add(journal + "t4.heat_network.hint", "Lay four or more heat pipes from a burning firebox to a boiler or a heat inlet. Copper pipe only carries a cherry-red heat.");
        add(journal + "t4.steam_engine", "Steam Power");
        add(journal + "t4.steam_hammer", "Hammer with Steam");
        add(journal + "t4.steam_hammer.hint", "Pick a shape on a steam hammer, give it steam at the back and heat from below, and let it smith steel.");
        add(journal + "t4.steam_engine.hint", "Pipe a boiler's steam into the back of a steam engine. At 2 bar it turns a shaft at 32 RPM.");
        add(journal + "t4.crusher", "Crushing Power");
        add(journal + "t4.crusher.hint", "Drive a crusher at 16 RPM or more. Ore comes out crushed, sometimes with a second piece and a bit of another mineral.");
        add(journal + "t4.blast_furnace", "Blast Furnace");
        add(journal + "t4.blast_furnace.hint", "Build a five-high refractory furnace, blow air into its tuyere and charge it with iron ore, coke and flux. Tap the pig iron.");
        add(journal + "t4.converter", "Bessemer Steel");
        add(journal + "t4.converter.hint", "Blow air through pig iron in a converter, with a coke to preheat it. Watch the flame: when it drops, the steel is done.");
        add(journal + "t4.automated_chain", "Automate a Chain");
        add(journal + "t4.automated_chain.hint", "Let a machine finish 64 items in a row with everything arriving and leaving by belt, chute, inserter or hopper, and nobody opening it.");
        add(journal + "t5.latex", "Tap a Rubber Tree");
        add(journal + "t5.latex.hint", "Jungle trees bleed latex. Plant one at home if the jungle is far; dandelions will do in a pinch.");
        add(journal + "t5.rubber", "Vulcanise Rubber");
        add(journal + "t5.rubber.hint", "Set latex in a sealed barrel, then roast the raw rubber at a low heat.");
        add(journal + "t5.cinnabar", "Mine Cinnabar");
        add(journal + "t5.cinnabar.hint", "Cinnabar is red as rust and hides in basalt and shale. Only steel will cut it.");
        add(journal + "t5.red_alloy", "Red Alloy");
        add(journal + "t5.red_alloy.hint", "Melt copper first, then add redstone: about two parts copper to three of redstone.");
        add(journal + "t5.wire", "Draw Wire");
        add(journal + "t5.wire.hint", "Draw copper rods thin on the anvil with a draw plate.");
        add(journal + "t5.circuit", "Basic Circuit");
        add(journal + "t5.circuit.hint", "Fit red alloy wire and redstone to a circuit board. Boards are paper soaked in creosote.");
        add(journal + "t5.dynamo", "Make Electricity");
        add(journal + "t5.dynamo.hint", "Turn a kinetic dynamo at 8 RPM or more. It makes 0.25 J/t for each RPM.");
        add(journal + "t5.cable", "Lay a Cable");
        add(journal + "t5.cable.hint", "Place an LV cable against a dynamo or a machine. Cables join on their own.");
        add(journal + "t5.first_machine", "Run a Machine");
        add(journal + "t5.first_machine.hint", "Connect a machine to a dynamo or battery box with cable and put something in it.");
        add(journal + "t5.turbine", "Steam Turbine");
        add(journal + "t5.turbine.hint", "Pipe steam into the back of a steam turbine. At 2 bar it settles at full output after ten seconds.");
        add(journal + "t5.macerator", "Macerate Ore");
        add(journal + "t5.macerator.hint", "Put ore in a macerator. It gives a second piece a quarter of the time.");
        add(journal + "t5.assembler", "Assemble a Part");
        add(journal + "t5.assembler.hint", "Load an assembler with the parts of one of its recipes and let it run.");
        add(journal + "t5.power_hammer", "Hammer with Electricity");
        add(journal + "t5.power_hammer.hint", "Pick a shape on a power hammer, or give it two ingots to weld. It heats the work itself.");
        add(journal + "t5.battery", "Store Energy");
        add(journal + "t5.battery.hint", "Charge a battery box to half. Dynamos and generators fill it when nothing else needs power.");
        add(journal + "t5.electric_heat", "Heat with Electricity");
        add(journal + "t5.electric_heat.hint", "Put an electric heater under a smelter or against a heat pipe and let it heat something.");
        add(journal + "t5.sulfuric_acid", "Sulfuric Acid");
        add(journal + "t5.sulfuric_acid.hint", "Mix sulfur dioxide, oxygen and water in a mixer. Roast sulfur for the gas.");
        add(journal + "t5.electrolysis", "Split Water");
        add(journal + "t5.electrolysis.hint", "Feed an electrolyser water. It gives hydrogen and oxygen, one tank each.");
        add(journal + "t5.alumina", "Roast Alumina");
        add(journal + "t5.alumina.hint", "Mix clay and sulfuric acid into alum, then roast it in an electric furnace or a roaster.");
        add(journal + "t5.aluminium", "Reduce Aluminium");
        add(journal + "t5.aluminium.hint", "Electrolyse alumina with a coke dust. It takes a long run and a lot of power.");
        add(journal + "t5.mv", "Medium Voltage");
        add(journal + "t5.mv.hint", "Sneak and right-click a machine with an MV upgrade kit.");
        add(journal + "t5.transformer", "Transform Voltage");
        add(journal + "t5.transformer.hint", "Join an LV and an MV network with a transformer and pass power through it.");
        add(journal + "t5.power_line", "Run a Power Line");
        add(journal + "t5.power_line.hint", "Serve a machine across 64 blocks of overhead span: poles, insulators and ACSR conductor.");
        add(journal + "t5.item_pipe", "Pipe Items");
        add(journal + "t5.item_pipe.hint", "Run item pipes from an extractor or an inserter to a chest. Items go to the nearest chest that takes them.");
        add(journal + "t5.storage", "Storage Controller");
        add(journal + "t5.storage.hint", "Connect a powered storage controller to four chests set to storage mode.");
        add(journal + "t5.stethoscope", "Listen to a Machine");
        add(journal + "t5.stethoscope.hint", "Right-click a running machine, cable or gearbox with a stethoscope.");
        add(journal + "t5.lightning", "Catch Lightning");
        add(journal + "t5.lightning.hint", "Stand a mast of three or more lightning rods on a Leyden jar bank and wait for a thunderstorm.");
        add(journal + "t5.ore_scanner", "Scan for Ore");
        add(journal + "t5.ore_scanner.hint", "Charge an ore scanner at a battery box, then hold right-click to scan around you.");
        add(journal + "t5.electric_chain", "Automate an Electric Chain");
        add(journal + "t5.electric_chain.hint", "Let an electric machine finish 64 items in a row at full power, fed and emptied by item pipe, with nobody opening it.");
    }

    /** Spec 9: anvils, the smithing screen, and tongs. */
    private void smithing() {
        String id = StrataIndustria.MOD_ID;
        for (var entry : ModBlocks.STONE_ANVILS.entrySet()) addBlock(entry.getValue(), title(entry.getKey().id()) + " Anvil");
        addItem(ModItems.TONGS_JAW, "Tongs Jaw");
        addItem(ModItems.TONGS, "Tongs");
        add("item." + id + ".tongs.tooltip", "In the off hand: hold hot metal without burns");
        add("heat." + id + ".too_hot", "Too hot to hold bare-handed. Tongs in your off hand would help.");
        add("death.attack." + id + ".hot_item", "%1$s held on to hot metal for too long");
        add("death.attack." + id + ".hot_item.player", "%1$s held on to hot metal for too long while fighting %2$s");
        add("container." + id + ".anvil", "Anvil");
        String status = id + ".anvil.";
        add(status + "shape", "%s \u00b7 %s blows");
        add(status + "shape_one", "%s \u00b7 1 blow");
        add(status + "hint", "Sneak + use with a hammer to pick, use to strike.");
        add(status + "too_cold", "Too cold. Back to the forge.");
        add(status + "no_hammer", "You need a hammer");
        add(status + "too_weak", "Needs an iron anvil for that metal");
        add(status + "output_full", "Take the finished piece first");
        add(status + "not_enough", "Needs %s of that metal");
        add(status + "no_plan", "Nothing to make from that");
        add(status + "bright", "Struck bright");
        add(status + "progress", "%s of %s blows");

        // Spec 7 and 8: mechanical power and machines.
        addBlock(ModBlocks.WOODEN_AXLE, "Wooden Axle");
        addBlock(ModBlocks.WOODEN_GEARBOX, "Wooden Gearbox");
        addBlock(ModBlocks.HAND_CRANK, "Hand Crank");
        addBlock(ModBlocks.WATER_WHEEL, "Water Wheel");
        addBlock(ModBlocks.MILLSTONE, "Millstone");
        addBlock(ModBlocks.BELLOWS, "Bellows");
        addItem(ModItems.WOODEN_GEAR, "Wooden Gear");
        add("container." + id + ".millstone", "Millstone");
        String kinetic = id + ".kinetic.";
        add(kinetic + "running", "%s RPM, %s / %s SU");
        add(kinetic + "idle", "Not turning");
        add(kinetic + "overstressed", "Overstressed (%s / %s SU)");
        add(kinetic + "incomplete", "Network incomplete");
        add(kinetic + "too_large", "Network too large");
        add(kinetic + "overspeed", "Overspeed: wooden parts cannot pass 64 RPM");
        String windmill = id + ".windmill.";
        add(windmill + "blocked", "Blocked: the sails need a clear 15 by 15 area");
        add(windmill + "few_sails", "Needs at least %s sails (has %s)");
        String belt = id + ".belt.";
        add(belt + "started", "Now use the belt on a second pulley");
        add(belt + "joined", "Pulleys belted together");
        add(belt + "taken", "That pulley already has a belt");
        add(belt + "not_parallel", "The pulleys must turn on parallel axles");
        add(belt + "not_in_line", "The pulleys must sit side by side, not on the same axle line");
        add(belt + "too_far", "Too far apart for one belt (8 blocks at most)");
        addBlock(ModBlocks.STEP_UP_GEARBOX, "Step-up Gearbox");
        addBlock(ModBlocks.PULLEY, "Pulley");
        addBlock(ModBlocks.WINDMILL_BEARING, "Windmill Bearing");
        addBlock(ModBlocks.WINDMILL_SAIL, "Windmill Sail");
        addItem(ModItems.LEATHER_BELT, "Leather Belt");
        addBlock(ModBlocks.SOAKING_BARREL, "Soaking Barrel");
        addItem(ModItems.RAW_HIDE, "Raw Hide");
        add("fluid_type." + id + ".lye", "Lye");
        add("fluid_type." + id + ".tannin", "Tannin");
        add("container." + id + ".soaking_barrel", "Soaking Barrel");
        String barrel = id + ".soaking_barrel.";
        add(barrel + "empty", "Add water, then something to soak");
        add(barrel + "open", "Sneak and use to seal the lid");
        add(barrel + "no_recipe", "Nothing here soaks into anything");
        add(barrel + "needs_more", "Needs %s more to use up the tank");
        add(barrel + "needs_fluid", "Not enough fluid; an empty bucket tips it out");
        add(barrel + "output_full", "Take out what is done");
        add(barrel + "working", "Soaking: %s%%");
        add(barrel + "lid_on", "Take the lid off first (sneak and use)");
        add(barrel + "poured_out", "%s tipped out of the barrel");
        add(barrel + "tank", "%s: %s / %s mB");
        add(barrel + "tank_empty", "Empty");
        add(barrel + "fluid.none", "Empty");
        add(barrel + "fluid.water", "Water");
        add(barrel + "fluid.lye", "Lye");
        add(barrel + "fluid.tannin", "Tannin");
        add(barrel + "fluid.other", "Fluid");
        add(kinetic + "limited_by", "speed limited by the source at %s %s %s");
        add(id + ".water_wheel.no_flow", "No water flow");
        add(id + ".water_wheel.blocked", "Blocked");
        String machine = id + ".machine.";
        add(machine + "empty", "Waiting for input");
        add(machine + "working", "Working");
        add(machine + "not_turning", "Needs a turning shaft");
        add(machine + "too_slow", "Too slow: needs %s RPM");
        add(machine + "no_recipe", "Cannot work that");
        add(machine + "output_full", "Output full");
        add(machine + "no_blade", "Needs a saw blade");
        addBlock(ModBlocks.SAW_MILL, "Saw Mill");
        addBlock(ModBlocks.TRIP_HAMMER, "Trip Hammer");
        addItem(ModItems.BARK, "Bark Strip");
        add("container." + id + ".saw_mill", "Saw Mill");
        add("container." + id + ".trip_hammer", "Trip Hammer");
        add("container." + id + ".core_sampler", "Core Sampler");
        add("container." + id + ".sluice", "Sluice");
        addBlock(ModBlocks.SLUICE, "Sluice");
        addItem(ModItems.WASHING_PAN, "Washing Pan");
        String sluice = id + ".sluice.";
        add(sluice + "empty", "Throw in crushed ore or placer gravel");
        add(sluice + "working", "Washing: %s%%");
        add(sluice + "no_water", "No water flow at the back");
        add(sluice + "no_recipe", "Washing out what it cannot use");
        String pan = id + ".washing_pan.";
        add(pan + "how", "Scoop up placer gravel or sand, or hold crushed ore in your other hand");
        add(pan + "cannot", "%s cannot be washed");
        add(pan + "no_water", "Stand in water to wash");
        add(pan + "holds", "Holds %s");
        addBlock(ModBlocks.CORE_SAMPLER, "Core Sampler");
        addItem(ModItems.CORE_SAMPLE, "Core Sample");
        String sampler = id + ".core_sampler.";
        add(sampler + "drill", "Drill");
        add(sampler + "idle", "Press Drill to take a core");
        add(sampler + "drilling", "Drilling");
        add(sampler + "not_turning", "Not turning");
        add(sampler + "too_slow", "Too slow: needs %s RPM");
        add(sampler + "output_full", "Take the last core out first");
        add(sampler + "done", "Core ready");
        String core = id + ".core_sample.";
        add(core + "cave", "Open cave");
        add(core + "at", "y %s");
        add(core + "range", "y %s\u2013%s");
        add(core + "layer", "%s: %s");
        add(core + "find", "%s: %s \u00d7%s");
        add(core + "graded", "%2$s %1$s");
        add(core + "layers", "Layers");
        add(core + "finds", "Ore and deposits");
        add(core + "barren", "No ore in this core");
        add(core + "where", "x %s, z %s");
        add(core + "origin", "Drilled at %s, %s, %s");
        add(core + "contains", "Shows %s");
        add(core + "scroll", "%s/%s, scroll");
        for (OreGrade grade : OreGrade.values()) add(id + ".grade." + grade.getSerializedName(), grade.getSerializedName());
        String hammer = id + ".trip_hammer.";
        add(hammer + "no_anvil", "No anvil in front");
        add(hammer + "not_turning", "Needs a turning shaft");
        add(hammer + "too_slow", "Too slow: needs %s RPM");
        add(hammer + "waiting", "Waiting for a hot workpiece");
        add(hammer + "working", "Working (%s / %s hits)");
        add(hammer + "output_full", "Output full");
        add(hammer + "anvil_busy", "Something else is on the anvil");

        // Spec 9.4 and 9.5: welding, flux and patterns.
        addBlock(ModBlocks.IRON_ANVIL, "Iron Anvil");
        addItem(ModItems.FLUX, "Flux");
        add(id + ".machine.shape", "Shape: %s");
        add(id + ".machine.shape.none", "none");
        add(id + ".machine.shape.hint", "Click for the next shape, right click for the one before");
    }

    /** Spec 6 to 8: metal names, the crucible screen, molds, cast parts and tools. */
    private void metals() {
        String id = StrataIndustria.MOD_ID;
        for (Metal metal : Metal.values()) {
            String name = metal == Metal.SLAG_METAL ? "Slag" : title(metal.id());
            add(id + ".metal." + metal.id(), name);
            if (metal.isVanilla() || !metal.hasIngot()) {
                // Copper's ingot and nugget are the vanilla items.
            } else {
                addItem(ModItems.INGOTS.get(metal), name + " Ingot");
                if (metal.hasNugget()) addItem(ModItems.NUGGETS.get(metal), name + " Nugget");
            }
            if (metal.hasPlate()) addItem(ModItems.PLATES.get(metal), name + " Plate");
            if (ModItems.RODS.containsKey(metal)) addItem(ModItems.RODS.get(metal), name + " Rod");
            if (ModItems.GEARS.containsKey(metal)) addItem(ModItems.GEARS.get(metal), name + " Gear");
            if (!metal.isToolMetal()) continue;
            if (!metal.isVanilla()) {
                for (var piece : ModItems.ARMOUR.get(metal).entrySet()) {
                    add(piece.getValue().get(), name + " " + title(piece.getKey().getName()));
                }
            }
            if (ModItems.PROSPECTOR_HEADS.containsKey(metal)) {
                addItem(ModItems.PROSPECTOR_HEADS.get(metal), name + " Prospector's Pick Head");
                addItem(ModItems.PROSPECTORS_PICKS.get(metal), name + " Prospector's Pick");
            }
            for (MoldType type : metal.toolTypes()) {
                addItem(ModItems.HEADS.get(metal).get(type), name + " " + title(type.id()));
                var tool = ModItems.TOOLS.get(metal).get(type);
                if (tool instanceof net.neoforged.neoforge.registries.DeferredItem<?> item) {
                    add(item.get(), name + " " + title(type.tool()));
                }
            }
        }
        add("container." + id + ".crucible", "Crucible");
        String status = id + ".crucible.status.";
        add(status + "too_cold", "Cold");
        add(status + "heating", "Heating up");
        add(status + "melting", "Melting... %s%%");
        add(status + "molten", "%s, molten");
        add(status + "molten_unknown", "Molten, but no known alloy");
        add(status + "solid", "Solid, needs more heat");
        add(status + "no_forge", "Needs a lit forge below");
        add(id + ".crucible.pour", "Pour");
        // The alloy name (%1$s) is left out to fit the line; the status line names it once it forms.
        add(id + ".crucible.hint", "Needs %2$s-%3$s%% %4$s, has %5$s%%");
        add(id + ".crucible.hint_parts", "%1$s %2$s: add %3$s %4$s");
        String problem = id + ".crucible.problem.";
        add(problem + "no_mold", "Put an empty mold in the mold slot");
        add(problem + "pouring", "Already pouring");
        add(problem + "not_molten", "The metal is not molten");
        add(problem + "not_enough", "Not enough metal to fill that mold");
        add(problem + "no_alloy", "That mix will not make a usable metal");
        add(id + ".mold.contents", "Holds %s (%s units)");
        add(id + ".mold.still_molten", "The metal is still molten. Let it cool first");
        addItem(dev.strataindustria.registry.PatternRegistry.PATTERN_BLANK, "Pattern Blank");
        addItem(dev.strataindustria.registry.PatternRegistry.SAND_FLASK, "Sand Flask");
        for (String shape : dev.strataindustria.registry.PatternRegistry.SHAPES) {
            String name = title(shape);
            addItem(dev.strataindustria.registry.PatternRegistry.PATTERNS.get(shape), name + " Pattern");
            addItem(dev.strataindustria.registry.PatternRegistry.SAND_MOLDS.get(shape), name + " Sand Mold");
        }
        add(id + ".pattern.need_flask", "You need a sand flask");
        addBlock(dev.strataindustria.registry.PrologueRegistry.BRICK_KILN, "Brick Kiln");
        addBlock(dev.strataindustria.registry.PrologueRegistry.CASTING_TABLE, "Casting Table");
        add("container." + id + ".brick_kiln", "Brick Kiln");
        String brickKiln = id + ".brick_kiln.status.";
        add(brickKiln + "empty", "Load clay to fire");
        add(brickKiln + "no_recipe", "That does not fire");
        add(brickKiln + "output_full", "Output full");
        add(brickKiln + "no_forge", "Needs a lit forge below");
        add(brickKiln + "too_cold", "The forge is too cold");
        add(brickKiln + "firing", "Firing (%s%%)");
        String table = id + ".casting_table.";
        add(table + "full", "The table is full");
        add(table + "nothing_set", "No castings to knock out");
        add(table + "still_molten", "The metal is still molten. Let it cool first");
        add(id + ".mold.broke", "The mold cracked apart");
        String prospect = id + ".prospect.";
        add(prospect + "nothing", "No ore nearby");
        String[][] sizes = {{"traces", "Traces of %s", "traces of %s"}, {"small", "Small %s", "small %s"},
                {"medium", "Medium %s", "medium %s"}, {"large", "Large %s", "large %s"}, {"very_large", "Very large %s", "very large %s"}};
        for (String[] size : sizes) {
            add(prospect + size[0], size[1]);
            add(prospect + size[0] + ".more", size[2]);
        }
        for (OreMineral mineral : OreMineral.values()) add(id + ".ore." + mineral.id(), mineral.id().replace('_', ' '));
        add(id + ".metal.slag_note", "Remelts to most of the metal that went in");
        for (String grade : new String[] {"rough", "standard", "fine"}) {
            add(id + ".quality." + grade, title(grade) + " quality");
        }
    }

    /** Recipe viewer pages (compat/jei); keys under {@code recipe_view.strataindustria.}. */
    private void recipeViewer() {
        String k = dev.strataindustria.compat.recipeview.RecipeText.KEY;
        add(k + "category.knapping", "Knapping");
        add(k + "category.clay_forming", "Clay Forming");
        add(k + "category.firing", "Firing");
        add(k + "category.charcoal_pit", "Charcoal Pit");
        add(k + "category.quern", "Grinding");
        add(k + "category.alloying", "Crucible Alloying");
        add(k + "category.casting", "Casting");
        add(k + "category.anvil", "Anvil Work");
        add(k + "category.bloomery", "Bloomery");
        add(k + "category.sawing", "Saw Mill");
        add(k + "category.washing", "Ore Washing");
        add(k + "category.barrel", "Soaking Barrel");
        add(k + "category.roasting", "Roasting");
        add(k + "category.coking", "Coke Oven");
        add(k + "category.firebox_fuel", "Firebox Fuel");
        add(k + "category.crushing", "Crushing");
        add(k + "category.machining", "Wiremill, Bender and Lathe");
        add(k + "category.mixing", "Mixer");
        add(k + "category.electrolysis", "Electrolyser");
        add(k + "category.assembling", "Assembler");
        add(k + "category.extruding", "Extruder");
        add(k + "crushing.both", "Crusher or macerator");
        add(k + "crushing.macerator_only", "Macerator only");
        add(k + "machining.mode", "%s, %s");
        add(k + "machining.mode.rod", "rod mode");
        add(k + "machining.mode.gear", "gear mode");
        add(k + "chemical.needs_tier", "Needs %s");
        add(k + "chemical.hot", "Comes out %s");
        add(k + "extruder.mode.cable_lv", "LV cable mode");
        add(k + "extruder.mode.cable_mv", "MV cable mode");
        add(k + "extruder.mode.pipe", "Pipe mode");
        add(k + "extruder.mode.item_pipe", "Item pipe mode");
        add(k + "heat.work", "Work at %s heat");
        add(k + "heat.weld", "Weld at %s heat");
        add(k + "anvil.blows", "%s blows");
        add(k + "anvil.blows.tip", "Iron takes one more blow, steel two more");
        add(k + "heat.melt", "Melts at %s heat");
        add(k + "heat.roast", "Roast at %s heat");
        add(k + "heat.bloom", "Fire to %s heat");
        add(k + "heat.fuel", "Up to %s heat");
        add(k + "heat.tooltip", "Heat it until it glows this colour");
        add(k + "time.seconds", "%s s");
        add(k + "time.minutes", "%s min");
        add(k + "time.minutes_seconds", "%s min %s s");
        add(k + "kinetic.rated", "at %s RPM");
        add(k + "chance", "%s%% chance");
        add(k + "washing.sluice_only", "in a sluice");
        add(k + "knapping.blows", "%s blows");
        add(k + "knapping.pick", "Sneak + use picks the shape");
        add(k + "firing.fuel", "Beside a fire of 450 \u00b0C or more");
        add(k + "charcoal_pit.cover", "Covered on every side");
        add(k + "alloying.share", "%s %s\u2013%s%%");
        add(k + "alloying.parts", "%s %s to %s %s");
        add(k + "alloying.parts_any", "Ingots, nuggets or ore, any multiple");
        add(k + "crucible.refractory", "Refractory crucible only");
        add(k + "casting.units", "%s units");
        add(k + "bloomery.per_level", "Per chimney level");
        add(k + "firebox.heat", "%s HU per tick");
    }
}
