package dev.strataindustria.datagen;

import dev.strataindustria.StrataIndustria;
import dev.strataindustria.electric.machine.ElectricMachineBlockEntity;
import dev.strataindustria.power.ElectricStatus;
import dev.strataindustria.rubber.TreeTapBlockEntity;
import java.util.function.BiConsumer;

/** English names and messages for tier 5 (electric). */
final class Tier5Language {
    private Tier5Language() {}

    static void add(BiConsumer<String, String> lang) {
        String id = StrataIndustria.MOD_ID;
        String item = "item." + id + ".", block = "block." + id + ".";
        lang.accept(item + "magnet", "Magnet");
        lang.accept(item + "copper_rod", "Copper Rod");
        lang.accept(item + "copper_wire", "Copper Wire");
        lang.accept(item + "lead_plate", "Lead Plate");
        lang.accept(item + "raw_rubber", "Raw Rubber");
        lang.accept(item + "compounded_rubber", "Compounded Rubber");
        lang.accept(item + "rubber", "Rubber");
        lang.accept(item + "latex_bucket", "Latex Bucket");
        lang.accept(item + "red_alloy_rod", "Red Alloy Rod");
        lang.accept(item + "red_alloy_wire", "Red Alloy Wire");
        lang.accept(item + "aluminium_wire", "Aluminium Wire");
        lang.accept(item + "steel_wire", "Steel Wire");
        lang.accept(item + "sulfuric_acid_bucket", "Sulfuric Acid Bucket");
        lang.accept(item + "alum", "Alum");
        lang.accept(item + "alumina", "Alumina");
        lang.accept(item + "draw_plate", "Draw Plate");
        lang.accept(item + "circuit_board", "Circuit Board");
        lang.accept(item + "basic_circuit", "Basic Circuit");
        lang.accept(item + "electric_motor", "Electric Motor");
        lang.accept(item + "lead_acid_cell", "Lead-Acid Cell");
        lang.accept(item + "mv_upgrade_kit", "MV Upgrade Kit");
        lang.accept(id + ".machine.upgraded", "%s machine");
        lang.accept(id + ".machine.upgraded_now", "Upgraded to %s");
        lang.accept(id + ".machine.already_mv", "Already MV");
        lang.accept(dev.strataindustria.metal.CrucibleStatus.REDSTONE_WAITING.key(), "Redstone needs molten copper");
        lang.accept("fluid_type." + id + ".latex", "Latex");
        lang.accept("fluid_type." + id + ".sulfuric_acid", "Sulfuric Acid");
        lang.accept("fluid_type." + id + ".brine", "Brine");
        lang.accept("fluid_type." + id + ".hydrogen", "Hydrogen");
        lang.accept("fluid_type." + id + ".oxygen", "Oxygen");
        lang.accept("fluid_type." + id + ".chlorine", "Chlorine");
        lang.accept(block + "tree_tap", "Tree Tap");
        lang.accept(block + "treated_log", "Treated Log");
        lang.accept(block + "utility_pole", "Utility Pole");
        lang.accept(block + "pole_insulator", "Pole Insulator");
        lang.accept("item." + id + ".unfired_insulator", "Unfired Insulator");
        lang.accept("item." + id + ".ceramic_insulator", "Ceramic Insulator");
        lang.accept("item." + id + ".acsr_conductor", "ACSR Conductor");
        lang.accept(id + ".soaking_barrel.fluid.creosote", "Creosote");
        String span = id + ".span.";
        lang.accept(span + "started", "Span started. Use the conductor on a second insulator");
        lang.accept(span + "joined", "Span strung (%s conductors used)");
        lang.accept(span + "not_insulator", "That is not a pole insulator");
        lang.accept(span + "already", "These insulators are already joined");
        lang.accept(span + "too_far", "Too far: a span reaches %s blocks");
        lang.accept(span + "full", "An insulator holds at most 4 spans");
        lang.accept(span + "blocked", "Something solid is in the way");
        lang.accept(span + "needs", "A span this long needs %s conductors");
        lang.accept(block + "lv_cable", "LV Cable");
        lang.accept(block + "mv_cable", "MV Cable");
        lang.accept(block + "kinetic_dynamo", "Kinetic Dynamo");
        lang.accept(block + "battery_box", "Battery Box");
        lang.accept(block + "lv_machine_hull", "LV Machine Hull");
        lang.accept(block + "electric_furnace", "Electric Furnace");
        lang.accept(block + "macerator", "Macerator");
        lang.accept(block + "wiremill", "Wiremill");
        lang.accept(block + "bender", "Bender");
        lang.accept(block + "lathe", "Lathe");
        lang.accept(block + "mixer", "Mixer");
        lang.accept(block + "assembler", "Assembler");
        lang.accept(block + "transformer", "Transformer");
        lang.accept(block + "energy_adapter", "Energy Adapter");
        lang.accept(id + ".transformer.readout.down", "Transformer, step down: %s J/t in on the MV side, %s J/t out on the LV side");
        lang.accept(id + ".transformer.readout.up", "Transformer, step up: %s J/t in on the LV side, %s J/t out on the MV side");
        lang.accept(id + ".energy_adapter.readout", "%s energy adapter: %s J/t (%s FE/t) out, %s J/t (%s FE/t) in");
        lang.accept(block + "electrolyser", "Electrolyser");
        lang.accept(block + "steam_turbine", "Steam Turbine");
        lang.accept(block + "combustion_generator", "Combustion Generator");
        String turbine = id + ".steam_turbine.", combustion = id + ".combustion_generator.";
        lang.accept(turbine + "running", "Rotor at %s%%, steam at %s bar, up to %s J/t");
        lang.accept(turbine + "no_steam", "No steam: needs at least %s bar");
        lang.accept(turbine + "spinning_down", "Spinning down: steam below %s bar");
        lang.accept(combustion + "empty", "Out of fuel");
        lang.accept(combustion + "tank", "%s: %s / %s mB");
        lang.accept(block + "electric_heater", "Electric Heater");
        lang.accept(block + "liquid_fuel_burner", "Liquid-Fuel Burner");
        lang.accept(block + "electric_pump", "Electric Pump");
        lang.accept(block + "kinetic_motor", "Kinetic Motor");
        String heater = id + ".electric_heater.", burner = id + ".liquid_fuel_burner.", motor = id + ".kinetic_motor.", pump = id + ".electric_pump.status.";
        lang.accept(heater + "idle", "Idle: no heat demand");
        lang.accept(heater + "heating", "Coil at %s °C, giving %s of up to %s HU/t");
        lang.accept(burner + "empty", "Out of fuel");
        lang.accept(burner + "no_fuel", "No fuel");
        lang.accept(burner + "idle", "Idle: no heat demand. %s %s / %s mB, %s °C");
        lang.accept(burner + "burning", "Burning: %s %s / %s mB, %s °C, giving %s HU/t");
        lang.accept(motor + "no_power", "No power");
        lang.accept(motor + "low_power", "Low power: not turning");
        lang.accept(pump + "no_power", "No power");
        lang.accept(pump + "no_water", "No water at the intake");
        lang.accept(pump + "no_outlet", "Nothing on the outlet");
        lang.accept(pump + "outlet_full", "Outlet full");
        lang.accept(pump + "pumping", "Pumping %s mB/t");

        // Spec 10.1: machine status lines and screen tooltips.
        String machine = id + ".electric_machine.";
        lang.accept(ElectricMachineBlockEntity.Status.EMPTY.key(), "Idle");
        lang.accept(ElectricMachineBlockEntity.Status.WORKING.key(), "Running");
        lang.accept(ElectricMachineBlockEntity.Status.LOW_POWER.key(), "Low power (%s%%)");
        lang.accept(ElectricMachineBlockEntity.Status.NO_POWER.key(), "No power");
        lang.accept(ElectricMachineBlockEntity.Status.NO_RECIPE.key(), "Can't process this");
        lang.accept(ElectricMachineBlockEntity.Status.OUTPUT_FULL.key(), "Output full");
        lang.accept(ElectricMachineBlockEntity.Status.OVERVOLTAGE.key(), "Overvoltage");
        lang.accept(ElectricMachineBlockEntity.Status.TOO_FAR.key(), "Too far from a source");
        lang.accept(ElectricMachineBlockEntity.Status.TANK_FULL.key(), "%s tank full");
        lang.accept(machine + "tank", "%s: %s / %s mB");
        lang.accept(machine + "tank_empty", "Empty");
        lang.accept(machine + "buffer", "Buffer: %s%%");
        lang.accept(machine + "eject_on", "Auto-eject on: outputs go into the block behind");
        lang.accept(machine + "eject_off", "Auto-eject off");
        lang.accept(machine + "mode_rod", "Mode: rods (one ingot makes two)");
        lang.accept(machine + "mode_gear", "Mode: gears (one ingot makes one)");

        // Spec 6.5: diagnostics and status lines.
        String electric = id + ".electric.";
        lang.accept(electric + "network", "%s network: %s / %s J/t, loss up to %s%%, stored %s / %s J");
        lang.accept(electric + "consumer", "%s J/t requested, %s J/t drawn (%s%% loss), %s");
        lang.accept(electric + "source", "Giving %s J/t, %s");
        lang.accept(electric + "storage", "%s / %s J, %s J/t %s");
        lang.accept(electric + "charging", "charging");
        lang.accept(electric + "discharging", "discharging");
        lang.accept(electric + "holding", "holding");
        lang.accept(electric + "no_demand", "spinning, no demand");
        lang.accept(electric + "limited_by_line", "Limited by overhead line (%s J/t)");
        lang.accept(electric + "limited_by", "Limited by %s cable (%s J/t)");
        lang.accept(ElectricStatus.NO_SOURCE.key(), "No power source");
        lang.accept(ElectricStatus.RUNNING.key(), "running");
        lang.accept(ElectricStatus.LOW_POWER.key(), "Low power (%s%%)");
        lang.accept(ElectricStatus.IDLE.key(), "idle");
        lang.accept(ElectricStatus.OVERVOLTAGE.key(), "Overvoltage: %s device on an %s network. Use a transformer");
        lang.accept(ElectricStatus.CABLE_OVERVOLTAGE.key(), "Overvoltage: %s cable at %s %s %s");
        lang.accept(ElectricStatus.TOO_FAR.key(), "Too far from a source (%s%% loss)");
        lang.accept(ElectricStatus.TOO_LARGE.key(), "Network too large");
        lang.accept(id + ".battery_box.charge", "%s battery: %s / %s J");

        // Spec 5.1: the tap's cup and why it is not dripping.
        lang.accept(id + ".tree_tap.cup", "%s: %s / %s mB");
        lang.accept(TreeTapBlockEntity.Status.NO_TREE.key(), "No living tree");
        lang.accept(TreeTapBlockEntity.Status.TAPPED_OUT.key(), "This tree is tapped out");
        lang.accept(TreeTapBlockEntity.Status.WORKING.key(), "Dripping");
        lang.accept(id + ".soaking_barrel.fluid.latex", "Latex");

        String subtitles = "subtitles." + id + ".";
        lang.accept(subtitles + "electric.overvoltage", "Electricity cracks");
        lang.accept(subtitles + "electric.spark", "Cable sparks");
        lang.accept(subtitles + "kinetic_dynamo.run", "Dynamo whirs");
        lang.accept(subtitles + "battery_box.charge", "Battery hums");
        lang.accept(subtitles + "block.pole_insulator.connect", "Span strung");
        lang.accept(subtitles + "block.pole_insulator.disconnect", "Span falls slack");
        lang.accept(subtitles + "block.tree_tap.place", "Tree tap knocked in");
        lang.accept(subtitles + "block.tree_tap.drip", "Latex drips");
        lang.accept(subtitles + "block.transformer.hum", "Transformer hums");
        lang.accept(subtitles + "block.transformer.switch", "Transformer switches");
        lang.accept(subtitles + "block.machine.upgrade", "Machine upgraded");
        lang.accept(subtitles + "block.machine.power_on", "Machine powers up");
        lang.accept(subtitles + "block.machine.power_off", "Machine powers down");
        lang.accept(subtitles + "block.machine.low_power", "Machine beeps");
        lang.accept(subtitles + "block.electric_furnace.run", "Electric furnace hums");
        lang.accept(subtitles + "block.macerator.grind", "Macerator grinds");
        lang.accept(subtitles + "block.wiremill.draw", "Wiremill draws wire");
        lang.accept(subtitles + "block.bender.press", "Bender presses");
        lang.accept(subtitles + "block.lathe.cut", "Lathe cuts");
        lang.accept(subtitles + "block.mixer.stir", "Mixer sloshes");
        lang.accept(subtitles + "block.assembler.work", "Assembler whirs");
        lang.accept(subtitles + "block.electrolyser.bubble", "Electrolyser bubbles");
        lang.accept(subtitles + "block.steam_turbine.run", "Steam turbine whines");
        lang.accept(subtitles + "block.steam_turbine.spin_down", "Steam turbine spins down");
        lang.accept(subtitles + "block.combustion_generator.ignite", "Combustion generator coughs");
        lang.accept(subtitles + "block.combustion_generator.run", "Combustion generator putters");
        lang.accept(subtitles + "block.liquid_fuel_burner.run", "Burner roars");
        lang.accept(subtitles + "block.electric_heater.run", "Electric heater hums");
        lang.accept(subtitles + "block.electric_pump.run", "Electric pump gulps");
        lang.accept(subtitles + "block.kinetic_motor.run", "Kinetic motor whines");
    }
}
